# Generated by Django 5.1.7 on 2025-03-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mod',
            name='is_published',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
