# Generated by Django 5.1.7 on 2025-03-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0002_mod_content_mod_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mod',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mod',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
